### ISSUE TITLE
GB2 Export does not work in 11.x

### ISSUE THREAD

**Issue by raulsv** [sakaicontrib/gradebook2#6]
Steps to reproduce the issue:

1. Create a grade item.
2. Try to export the gradebook structure (selecting any of the export options). The export fails: no file is downloaded.

**Comment by raulsv** [comment]
Hi @ottenhoff

[PR](https://github.com/sakaicontrib/gradebook2/pull/10/commits/54243e1d6c633197e880f3c8432080306def7838) done. Regards,

Raúl

**Comment by ottenhoff** [comment]
PR #10  closes this
