### ISSUE TITLE
GB2 Import does not work in 11.x

### ISSUE THREAD

**Issue by raulsv** [sakaicontrib/gradebook2#7]
Steps to reproduce the issue:

1. Create a grade item.
2. Export the gradebook structure by selecting the 'Full Gradebook (Grades & Structure)' option.
3. Try to import the file from step 2 by selecting the  'Full Gradebook (Grades & Structure)' option. Nothing happens. This error is shown in log:

```
java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/StreamingNotSupportedException
	at org.apache.tika.parser.pkg.ZipContainerDetector.detect(ZipContainerDetector.java:88)
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:77)
```

**Comment by ottenhoff** [comment]
Hi @raulsv , there is no maintainer for GB2. Can you submit a PR?

**Comment by raulsv** [comment]
Hi @ottenhoff 

I'm rather busy right now. When I have some free time I will do the PR. Regards,

Raúl

**Comment by raulsv** [comment]
PR done: https://github.com/sakaicontrib/gradebook2/pull/8
